# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903c8ddc5f3d6d536b57705b3c75d7e649fef2500036cb0420d30760b58c6d2ed8e136ca42277dd647fe6edeba2bcd7d8823325bce6a757d6966e236dc17991d

test:
  secret_key_base: 9d0a28c0acc4bb754edd5b15a64c3dc73d510cc34a97ced4ab429ab5915bd34a6ab3dbcc1d670185094d58483e33af369d9859cb205e2a4e161902967055b6fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
